name: buttplug
description: Buttplug Sex Toy Control Library Client implementation in Dart
version: 1.0.0
homepage: https://buttplug.io

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  lints: ^6.0.0
  test: ^1.28.0
